### ISSUE TITLE
Hourly injester will miss trips

### ISSUE THREAD

**Issue by ezheidtmann** [CityofSantaMonica/mds-provider-services#20]
When `start_time` and `end_time` query parameters are both present, the MDS spec requires providers to return trips which lie entirely within the range. So unless I'm missing something, the hourly injester script will never retrieve trips which span the hour boundary.

**Comment by thekaveman** [comment]
It's possible, sure. You can always expand the window - those are parameters, they can be set from the command line `--start_time`, `--end_time`, and/or `--duration`

**Comment by ezheidtmann** [comment]
Sorry, I could have been clearer. Unless I'm mistaken, the `hourly.sh`, if run as an hourly cronjob, will miss trips which are in progress at the turn of the hour. This could be fixed by changing the `--duration` value to a number larger than 3600; the greater the overlap the better. 

I'm happy to work on a failing test case and a PR if you think this is important to fix. Or if you're not using it, we could delete `hourly.sh` so folks don't get steered the wrong way.

**Comment by thekaveman** [comment]
Trips that are in progress should not be reported anyway - the Provider API is all about historical information, events that already happened. The trip becomes available on the endpoint in the hour that it ends, not the hour that it begins.

I hope some of this is cleared up by the changes staged for MDS `0.3.0` related to the time query parameters (and indeed, the representation of time itself). I think the core of the issue you're raising is perhaps a bit of ambiguity in these parameters, particularly as it relates to paging - which has hopefully been cleared up.

Related:

CityofLosAngeles/mobility-data-specification#125
CityofLosAngeles/mobility-data-specification#139
CityofLosAngeles/mobility-data-specification#179

**Comment by ezheidtmann** [comment]
Thanks for the reference! Glad the query interface will be changing in 0.3.x; that's definitely the underlying issue here.

But as far as I can tell, this issue still stands for 0.2.x consumers. The trips that will be missed are those that were in progress at the previous turn of the hour. 

For example, imagine a 10-minute trip from 10:55am to 11:05am.  We run `hourly.sh` at 11:45am; this performs a query for trips where `start_time >= "10 am"` and `end_time <= "11 am"`. Clearly the trip of interest will not be returned because its `end_time` does not meet the criteria.

Then we run `hourly.sh` again at 12:45pm. This performs a query for trips where `start_time >= "11 am"` and `end_time <= "12 pm"`. The trip of interest will not be returned here either, because its `start_time` is too early.

I believe that increasing the `duration` parameter in `hourly.sh` should resolve this issue, with the exception of trips longer than the overlap time. For example, a query with a 2-hour window run every hour would get all trips less than an hour in length, but could miss certain trips longer than an hour if they occur at the right time of the hour.

**Comment by ezheidtmann** [comment]
Just a quick update to say I've verified that at least one provider is following the 0.2.x spec in this regard, and the behavior I described is happening. Until 0.3.x is widely adopted, I just want to make sure that other consumers are aware & compensating appropriately.

**Comment by thekaveman** [comment]
Thanks for digging in to this so thoroughly. 

I think your analysis is correct, and as you have found, it is possible to miss trips if running this `hourly.sh` script exactly as-is. That being said, I'm not sure there is much else I want to do from a change perspective - those scripts are more helpers/examples of calling into the underlying `docker` services. Rather than try and cover every possible corner-case in these scripts, I'd like to leave this up to users to query the time window as they see fit. 

And as already noted, hopefully by `0.3.0` most of this will change and perhaps even the `hourly.sh` script will go away (or be significantly altered anyway) at that time.

**Comment by thekaveman** [comment]
Removing these in the next release: 3f69e97
