### ISSUE TITLE
Difficulties authenticating Bird API

### ISSUE THREAD

**Issue by asadowns** [CityofSantaMonica/mds-provider-services#25]
We are having some trouble with the ingest script.

We have followed the instruction steps 0 - 3 in this repo on the `master` branch. And are currently stuck on the ingestion step because we cannot pass the correct config. We are passing the default `.config`.

`ingest/bin/download.sh . --providers 2411d395-04f2-47c9-ab66-d09e9e3c3251 --status_changes --start_time 1544774400 --end_time 1548603770` - This does not error but returns no data.

`ingest/bin/validate.sh --providers Bird --status_changes` - This returns a 403 unauthorized

Here is the contents of `.config`s we've tried. We've tried multiple other variations of this config. Using both the examples provided, using the default config, and using provider-specific configs. Also passing `headers` in a number of ways.

```
[DEFAULT]
    ref = master
    auth_type = Bird
    token = {OUR_TOKEN}
    ref = master
    mds_api_url = https://mds.bird.co
    [headers]
      App-Version = 3.0.0
```

```
[DEFAULT]
    ref = master

[2411d395-04f2-47c9-ab66-d09e9e3c3251]
    auth_type = Bird
    token = {OUR_TOKEN}
    ref = master
    mds_api_url = https://mds.bird.co
[headers]
  App-Version = 3.0.0
```

We are wondering if there is an issue with the following block of code:

```
    # parse any headers from the config to a dict
    for p in providers:
        headers = getattr(p, "headers", None)
        if headers and isinstance(headers, str):
            p.headers = json.loads(headers)
```

this block of code expects the configuration of a provider to be nested. because ConfigParser is being used, this will not work. in the library code for `p.configure(...)`

    ```def configure(self, config, use_id=False):
        """
        Merge Provider-specific data from :config: with this provider.

        Returns a new Provider with the merged data.

        :use_id: is a flag that, when True, will lookup this Provider by provider_id inside the :config:
        (e.g. for using a dict of configuration for different Providers). If the provider_id isn't found,
        returns this Provider un-modified.
        """
        if use_id:
            if self.provider_id in config:
                config = config[self.provider_id]
            elif str(self.provider_id) in config:
                config = config[str(self.provider_id)]
            else:
                return self

        _kwargs = { **vars(self), **config }
        return Provider(**_kwargs)```

this doesn't handle nested configs for the config var.
^ add that to the issue

**Comment by thekaveman** [comment]
Yeah, unfortunately `configparser` doesn't support nested/sub-sections. The block of code you mentioned: 
```python
# parse any headers from the config to a dict
for p in providers:
    headers = getattr(p, "headers", None)
    if headers and isinstance(headers, str):
        p.headers = json.loads(headers)    
```

is parsing a JSON dict-like `headers` item:

```console
[2411d395-04f2-47c9-ab66-d09e9e3c3251]
    headers = { "APP-Version": "3.0.0" }
```

This is probably not very intuitive from the example file. Then again, custom headers like this are not part of MDS, so this is non-standard behavior for sure.

**Comment by thekaveman** [comment]
Closing, with the above instructions for today's code.

Will look to simplify all of this with #28.
