### ISSUE TITLE
Data Ingestion Errors in SQL write to DB and payload validation

### ISSUE THREAD

**Issue by conor-mclaughlin-br** [CityofSantaMonica/mds-provider-services#35]
When running the updated data ingestion script from the latest version of the repository, I receive a series of errors when validating the payload and then writing it to the local DB. This follows seemingly successful payload retrieval which is logged to the console (ie. _Got payload with 92 status_changes_)

**Ingest Command:** 
`docker-compose run --rm ingest --start_time 1546214400 --end_time 1546387200 --duration 21600 --status_changes --providers Bird`

**Validation Error:** 
`Payload error in data.status_changes[91]
{'provider_id': '2411d395-04f2-47c9-ab66-d09e9e3c3251', 'provider_name': 'bird', 'device_id': '966fcd10-5ac5-4160-8334-c354f5640f95', 'vehicle_id': 'IWVDM', 'vehicle_type': 'scooter', 'propulsion_type': ['electric'], 'event_type': 'removed', 'event_type_reason': 'maintenance', 'event_time': 1546386022.729, 'event_location': {'type': 'Feature', 'properties': {'timestamp': 1546386022.729}, 'geometry': {'type': 'Point', 'coordinates': [-118.48199500000001, 33.99933166666666]}}, 'battery_pct': 0.06} is not valid under any of the given schemas`

**SQL Error**: Data in the attached text file - appears to result in the SQL insert into the DB
[bird_error.txt](https://github.com/CityofSantaMonica/mds-provider-services/files/2725801/bird_error.txt)

Are you aware of any known validation + DB ingest issues which might pertain to this data, or any reason why these errors might be triggered? Thanks!

**Comment by thekaveman** [comment]
**Validation Error:**
As indicated by the error message, the data you pasted is not valid. 

`{'event_type': 'removed', 'event_type_reason': 'maintenance'}` is not a valid combination according to the [table of events from MDS 0.2.1](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/0.2.1/provider#event-types).

**SQL Error:**
This is related to your table definition expecting data type conversions from the raw JSON. The staging capabilities in `mds-provider` handle this, or you have to convert the raw data before insert. See the related discussions on CityofSantaMonica/mds-provider#66 and #37.

I'm closing this, if you have further questions feel free to open new issue(s).
