### ISSUE TITLE
Validation step in ingest can't be configured to provider version

### ISSUE THREAD

**Issue by yoimnik** [CityofSantaMonica/mds-provider-services#55]
the validation step points to https://raw.githubusercontent.com/CityOfLosAngeles/mobility-data-specification/master/provider/status_changes.json

but provider versions shoudl be configurable

following along in here:
https://github.com/CityOfLosAngeles/mds-validator/issues/1

**Comment by thekaveman** [comment]
You can use the [`--ref`](https://github.com/CityofSantaMonica/mds-provider-services/tree/master/ingest#--ref-ref) option on the command line, or the [`ref`](https://github.com/CityofSantaMonica/mds-provider-services/blob/master/ingest/.config.sample#L13) key in the ingest config to configure this. 

`master` is just the default.

**Comment by yoimnik** [comment]
ahh okay, i didn't know

https://raw.githubusercontent.com/CityOfLosAngeles/mobility-data-specification/0.2.1/provider/status_changes.json
https://raw.githubusercontent.com/CityOfLosAngeles/mobility-data-specification/0.2.1/provider/trips.json

existed -- i just realized i should also check for tags instead of branches in that repo for versions

thanks!
