### ISSUE TITLE
Ingestion Backfills do not need to overlap in MDS  >= 0.3

### ISSUE THREAD

**Issue by zaksoup** [CityofSantaMonica/mds-provider-services#67]
# What happens now?
Currently, when providing a `--start-time`, `--end-time`, and `--duration` the behavior is to run "backfill" ingestion. Due to the behavior of filtering trips by `start_time` and `end_time` (as opposed to `min_end_time` and `max_end_time`) it's necessary to make overlapping queries when backfilling to catch trips that would otherwise have started before the cut-off and ended after, and therefor be filtered out.

# What should happen?
In MDS 0.3 and newer trips are filtered by `min_end_time` and `max_end_time`. Since this catches all trips that ended within a certain period regardless of their start time this is not susceptible to the 0.2 issue of trips being filtered out at the boundaries of filter criteria.

# Why is this an issue
With the default offset of `duration / 2` it results in the total time to scrape being two times the time to scrape without any overlap. For large ingestion jobs this is a serious time investment that we're interested in reducing for batch ingestion jobs.

# What should change?
I'm opening this issue to discuss adding code to the [`main.py` ingest method](https://github.com/CityofSantaMonica/mds-provider-services/blob/86254046108d5aa0f27e2dc68bcb7b4b35588d62/ingest/main.py#L160-L199) that would detect the version provided in `config.json` and if the version is >= 0.3 set the offset to `0`.

If this seems like a reasonable solution we (Remix) are happy to submit a pull request for review with the suggested changes.

**Comment by thekaveman** [comment]
Indeed this is probably an overly complex solution to some of the concerns originally raised in #20. As you note, MDS 0.3.0+ has largely obviated the need to do this sliding window backfill.

In preparation for MDS 0.4.x support in `mds-provider`, we have a [tracking issue](https://github.com/CityofSantaMonica/mds-provider/issues/79) which includes dropping support for 0.2.x (as per MDS [*Ongoing Version Support*](https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/ReleaseGuidelines.md#ongoing-version-support) guidelines). I'd be in favor of doing the same here, including removing this backfill overlap.

If this is a serious pain in the meantime, happy to take a PR as per your suggestion (though I would rather simplify the whole thing).

**Comment by zaksoup** [comment]
I'm fine with removing the sliding backfill feature entirely as part of dropping 0.2 and adding 0.4. Given that I'm closing this issue. For my own needs I can run a fork of this code where I've already removed the sliding backfill until 0.4 lands on master...
