### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by krithin** [CityofSantaMonica/mds-provider-services#8]
Hi!

I'm using the fake MDS generator as one element of a docker-compose setup that ingests MDS data, in lieu of hitting real MDS provider endpoints. This has been really useful so far, thanks!

docker-compose only lets us refer to external git repositories by branch name or tag name, and not by commit SHA. It would be great if we could refer to a stable version of the fake MDS generator; are you open to tagging specific commits here as stable-ish releases?

Thanks!

**Comment by thekaveman** [comment]
Yes, definitely open to it. 

I think after #5 is merged, I'll feel good about marking a stable release, same for `mds-provider`.

**Comment by thekaveman** [comment]
https://github.com/CityofSantaMonica/mds-provider-services/tags
